randycoulman/mix_test_interactive

lib/mix_test_interactive.ex

Ideally, the program will accept commands without a trailing newline, but that looks to be very difficult in Elixir/Erlang.  So for now, this requires the user to hit `Enter` to run a command.
One possible solution is to use `ex_ncurses`, but that might cause some portability problems. However, we might need it for later features so we'll consider it at that time.

✨ Add quit command

---

lib/mix_test_interactive.ex
lib/mix_test_interactive/port_runner.ex
lib/mix_test_interactive/runner.ex
priv/zombie_killer
test/mix_test_interactive/port_runner_test.exs
test/mix_test_interactive/runner_test.exs

Runs `mix test` in ANSI color mode at startup and after each command (other than `q`).
A side effect of this is that hitting `Enter` (empty command) will also re-run the tests, which is the desired feature.

✨ Run tests each time through the loop

---

.circleci/config.yml
lib/mix_test_interactive.ex
lib/mix_test_interactive/config.ex
lib/mix_test_interactive/port_runner.ex
lib/mix_test_interactive/runner.ex
mix.exs
mix.lock
test/mix_test_interactive/config_test.exs
test/mix_test_interactive/port_runner_test.exs
test/mix_test_interactive/runner_test.exs

Support the same set of configuration options as `mix-test.watch`, including the ability to pass command-line arguments on to `mix test`.
Also, add mix.lock checksum to CI cache key. Now that we have a mix dependency, we can have a more focused CI cache based on `mix.lock`'s checksum.

✨ Support all mix-test.watch configuration options

---

lib/mix_test_interactive.ex
lib/mix_test_interactive/command_processor.ex
test/mix_test_interactive/command_processor_test.exs

- Using `IO.getn` was resulting in double test runs.
- We were re-running tests on unrecognized commands.
- `Ctrl-D` (EOF) wasn't being handled properly
Switched to using `IO.gets` to read commands.
Extracted a CommandProcessor for handling the commands; it handles `:eof` the same way as the `q` command, trims whitespace from string commands, and ignores unknown commands.
The CommandProcessor takes and returns a config; it currently doesn't make any changes to it, but future commands will.
The main loop now only runs the tests when a non-quit command is recognized.

🐛 Fix issues with listener loop

---

lib/mix_test_interactive.ex
lib/mix_test_interactive/command_processor.ex
lib/mix_test_interactive/interactive_mode.ex
test/mix_test_interactive/command_processor_test.exs

New InteractiveMode module now house the main loop.
Also, rename `CommandProcessor.process_command` to `call`.

♻️ Extract main loop to new module

---

lib/mix_test_interactive.ex
lib/mix_test_interactive/application.ex
lib/mix_test_interactive/config_store.ex
lib/mix_test_interactive/interactive_mode.ex
lib/mix_test_interactive/message_inbox.ex
lib/mix_test_interactive/paths.ex
lib/mix_test_interactive/watcher.ex
mix.exs
mix.lock
test/mix_test_interactive/message_inbox_test.exs
test/mix_test_interactive/paths_test.exs

Brings in `Watcher` and friends from mix-test.watch.
Introduces a `ConfigStore` agent for storing the config and sharing it between the watcher and the interactive mode.

✨ Run tests after files change

---

lib/mix_test_interactive/command_processor.ex
lib/mix_test_interactive/config.ex
lib/mix_test_interactive/port_runner.ex
test/mix_test_interactive/command_processor_test.exs
test/mix_test_interactive/config_test.exs
test/mix_test_interactive/port_runner_test.exs
test/mix_test_interactive_test.exs

New `p` command takes a list of files (or file:line specs) and runs only those files.
`c` command clears the filename filter.

✨ Allow restricting the files to run

---

lib/mix_test_interactive/command_processor.ex
lib/mix_test_interactive/config.ex
test/mix_test_interactive/command_processor_test.exs
test/mix_test_interactive/config_test.exs

`s` restricts to stale files; `a` returns to running all files
Both commands retain any filename filters previously set.

✨ Add stale command

---

lib/mix_test_interactive/command_processor.ex
lib/mix_test_interactive/config.ex
test/mix_test_interactive/command_processor_test.exs
test/mix_test_interactive/config_test.exs

`f` will run only failed tests; `a` will go back to running all tests.

✨ Add command to run only failed tests

---

lib/mix_test_interactive/command_processor.ex
lib/mix_test_interactive/commands.ex
lib/mix_test_interactive/interactive_mode.ex
test/mix_test_interactive/command_processor_test.exs

Extracts commands to their own modules and use them to only run relevant commands and show them in the usage message.

✨ Show only relevant commands in usage

---

lib/mix_test_interactive/command_processor.ex
lib/mix_test_interactive/commands.ex
lib/mix_test_interactive/interactive_mode.ex
test/mix_test_interactive/command_processor_test.exs

Preserve output space by normally showing a short usage message.
Adds a `?` command to show the full usage message.

✨ Only show full usage when asked

---

lib/mix_test_interactive/command/pattern.ex
test/mix_test_interactive/command_processor_test.exs

We want to allow changing to a different pattern without having to switch back to s, f, or a mode first.

🐛 Allow consecutive p commands

---

lib/mix_test_interactive/config.ex
lib/mix_test_interactive/interactive_mode.ex
lib/mix_test_interactive/port_runner.ex
lib/mix_test_interactive/runner.ex
lib/mix_test_interactive/watcher.ex
test/mix_test_interactive/config_test.exs
test/mix_test_interactive/port_runner_test.exs

When no tests match a given pattern, we would instead run all tests.
Now, we show a message indicating that no tests were found.

✨ Show failure message when no tests match

---

README.md
lib/mix_test_interactive/config.ex
lib/mix_test_interactive/port_runner.ex
test/mix_test_interactive/config_test.exs
test/mix_test_interactive/port_runner_test.exs

Because `mix test.interactive` is geared towards running `mix test` interactively, some of the configuration options inherited from mix-test.watch don't make as much sense.
With interactive mode, changing the CLI executable from `mix` to `iex -S mix` doesn't work, so we now hard-code that to `mix`.  If there is another use case for this option, I'm willing to reconsider.
The support for running multiple tasks was not ideal, as it would pass the same arguments to all of the commands, which is probably not what we really want (see https://github.com/lpil/mix-test.watch/issues/80 for example).
However, there is still a use for defining a task alias that runs `mix test` under the hood, so we still allow configuration of a single task.  However, `mix test.interactive` assumes that the custom …

🔥 Remove some config options

---

README.md
lib/mix_test_interactive/config.ex
test/mix_test_interactive/config_test.exs

Initializes the matching patterns from the command-line.  Patterns are applied as if they were specified by the `p` command.
Ignores any filenames provided by the `--include` or `--only` flags.
In order for this to work properly, we need to know all of the options and their types supported by `mix test` in order to properly parse the command line.  Otherwise, a user could run `mix test.interactive --trace pattern` and the option parser would treat `--trace` as a string with the value `pattern` rather than as a boolean flag with a separate `pattern`.
The downside to this is that it introduces a compatibility issue if a future version of `mix test` adds a new command-line option. Until we update our list, users will not be able to pass the new option through `mix test.interactive`.
At …

✨ Initialize patterns from command-line

---

lib/mix_test_interactive/port_runner.ex
test/mix_test_interactive/port_runner_test.exs

As reported in https://github.com/lpil/mix-test.watch/issues/103, the code we adopted from mix-test.watch was always running `mix test` without arguments on Windows even if a custom command or other options were provided.
Now, we run the proper command on Windows.
As reported in https://github.com/lpil/mix-test.watch/pull/104, I also had trouble getting past the quote and backslash issues with the ANSI-enable command on Windows. Plus, in my experimenting, I found that a basic Windows command shell doesn't support ANSI commands.
Therefore, we do not enable ANSI output when running on Windows.
If someone is able to figure out the quoting/backslash issues and help fix the problem, I'm open to solutions.

🐛 Use proper command on Windows

---

README.md
lib/mix_test_interactive/command.ex
lib/mix_test_interactive/command/toggle_watch_mode.ex
lib/mix_test_interactive/command_processor.ex
lib/mix_test_interactive/config.ex
lib/mix_test_interactive/interactive_mode.ex
lib/mix_test_interactive/watcher.ex
test/mix_test_interactive/command_processor_test.exs
test/mix_test_interactive/config_test.exs

Allows file-watching mode to be turned on or off (on by default).
Turn off at startup with `mix test.interactive --no-watch`.
Once running, toggle watch mode on/off with the `w` command.

✨ Enable/disable watch mode

---

lib/mix_test_interactive/interactive_mode.ex
lib/mix_test_interactive/port_runner.ex
lib/mix_test_interactive/runner.ex
test/mix_test_interactive/port_runner_test.exs
test/mix_test_interactive/runner_test.exs

Instead of passing the Settings to the runner, only pass the CLI args.
This will make it easier to have (almost) end-to-end tests, and also isolates the handling of the `no matching tests` error higher in the call stack.

♻️ Pass CLI args to runner

---

lib/mix_test_interactive/command_processor.ex
lib/mix_test_interactive/settings.ex

When splitting out `Settings` from `Config`, there were a number of functions that take a `Settings` struct, but referred to it as `config` which was confusing.

♻️ Rename function args

---

lib/mix_test_interactive.ex
lib/mix_test_interactive/interactive_mode.ex
test/mix_test_interactive/end_to_end_test.exs

Fixes #43 
When a command is entered during a long test run, a GenServer timeout would be raised.
To fix this, `InteractiveMode.process_command` now uses `cast` instead of `call` so that the read loop doesn't block on commands.
To make this work, we now have to use `System.stop` for the `quit` command rather than returning a `:quit` atom and allowing the loop to exit naturally.
`System.stop` takes just enough time that it seems like the quit command was ignored, so I also added a `Shutting down...` message to make it clear that something is happening.

🐛 Avoid timeout errors

---

.gitignore
LICENSE.md
README.md
mix.exs

Besides other documentation changes, this commit ensures the generated
HTML doc for HexDocs.pm will become the source of truth for this Elixir
library and leverage on latest features of ExDoc.

Misc doc changes

---

.circleci/config.yml
.tool-versions
lib/mix_test_interactive/settings.ex
lib/mix_test_interactive/watcher.ex

**BREAKING:** Dropped support for all Elixir versions prior to 1.11 which matches the [list of supported releases](https://hexdocs.pm/elixir/1.15.5/compatibility-and-deprecations.html).
Use latest Elixir/Erlang versions locally.
Update list of versions in CI to include all supported versions.

💥 Update supported Elixir versions

---

.formatter.exs
lib/mix/tasks/test/interactive.ex
lib/mix_test_interactive/application.ex
lib/mix_test_interactive/command/all_tests.ex
lib/mix_test_interactive/command/failed.ex
lib/mix_test_interactive/command/help.ex
lib/mix_test_interactive/command/pattern.ex
lib/mix_test_interactive/command/quit.ex
lib/mix_test_interactive/command/run_tests.ex
lib/mix_test_interactive/command/stale.ex
lib/mix_test_interactive/command/toggle_watch_mode.ex
lib/mix_test_interactive/command_processor.ex
lib/mix_test_interactive/config.ex
lib/mix_test_interactive/interactive_mode.ex
lib/mix_test_interactive/port_runner.ex
lib/mix_test_interactive/settings.ex
lib/mix_test_interactive/test_files.ex
lib/mix_test_interactive/watcher.ex
mix.exs
mix.lock
test/mix_test_interactive/command_processor_test.exs
test/mix_test_interactive/end_to_end_test.exs
test/mix_test_interactive/message_inbox_test.exs
test/mix_test_interactive/paths_test.exs
test/mix_test_interactive/pattern_filter_test.exs
test/mix_test_interactive/port_runner_test.exs
test/mix_test_interactive/runner_test.exs
test/mix_test_interactive/settings_test.exs

Adds [Styler](https://github.com/adobe/elixir-styler) to auto-format the codebase.
- Run `mix format` using Styler
- Fix code that broke
- Rename `@def` in `PatternFilterTest` to avoid a bug in Styler

🎨 Adopt Styler for formatting

---

README.md
lib/mix/tasks/test/interactive.ex

Now `mix help test.interactive` will show a summary of usage and configuration information for the task.

📝 Add documentation to the task

---

.circleci/config.yml
.tool-versions

Drop CI support for 1.11 (no longer supported upstream) and add for 1.16.

⬆️ Upgrade to latest Elixir version

---

mix.exs

Officially drop support for 1.11 and prior.

💥 Update Elixir version in mix.exs

---

mix.exs

In #72, we upgraded to file_system 1.0. However, popular libraries like `phoenix_live_reload` still depend on v0.3, which results in a version conflict.
Because this libarary works with either version, we can safely loosen the version specification to avoid conflicts in client projects.

⬇️ Allow file_system 0.3

---

mix.exs

There isn't actually a file_system v0.3 version; I was misled by a commit I saw in the phoenix_live_reload repo.
This change allows both v0.2.x and v1.x of file_system to avoid conflicts with other libraries.

⬇️ Allow file_system 0.2

---

lib/mix_test_interactive/watcher.ex
mix.exs

The :isdir, :closed, and :attribute events likely don't need to be monitored to run tests, and at least the :attribute event is causing problems for projects that use the Domo library for validation. This is because the Domo library causes a delayed file read event to occur on some elixir files in the lib directory, which causes their atime attribute to be updated. This is happening after the test run kicks off, and then it causes a second test run to occur.

Ignore some filesystem events emitted by inotify

---

.github/workflows/ci.yml
mix.exs

We officially support all [supported Elixir releases](https://hexdocs.pm/elixir/1.17.2/compatibility-and-deprecations.html).
With the release of Elixir 1.17, Elixir 1.12 is no longer supported so we drop support here as well.

💥 Drop support for Elixir 1.12

---

.formatter.exs
README.md
lib/mix_test_interactive/config.ex
lib/mix_test_interactive/port_runner.ex
lib/mix_test_interactive/settings.ex
test/mix_test_interactive/config_test.exs
test/mix_test_interactive/port_runner_test.exs
test/mix_test_interactive/runner_test.exs

Allow a custom command (with optional arguments) to be used in place of `mix`.
Also:
- Some code cleanups
- Add documentation for all configuration options (several were missing previously)
Closes #63

✨ Allow custom command in place of mix

---

lib/mix_test_interactive/pattern_filter.ex
test/mix_test_interactive/pattern_filter_test.exs

Previously, when given multiple patterns, we would not do any file filtering if any of the patterns was a `file:line`-style pattern. Instead, we'd pass all of the patterns to `mix test` literally.
Now, we run normal file filtering for any non-`file:line`-style patterns and concatenate the results with any `file:line`-style patterns.

✨ Make pattern filtering more flexible

---

README.md
lib/mix/tasks/test/interactive.ex

Earlier, we added missing documentation for configuration options to the README, but forgot to add them to the mix task's `@moduledoc`. This corrects that oversight.

📝 Add all config options to mix task docs

---

CHANGELOG.md
README.md
lib/mix_test_interactive.ex
mix.exs

Includes README update for more flexible pattern filtering and a minor formatting cleanup.

🏷️ Prepare 3.2.0 release

---

lib/mix_test_interactive/port_runner.ex
test/mix_test_interactive/port_runner_test.exs

Given a configuration such as:
```elixir
config :mix_test_interactive,
command: {"elixir", ["--sname", "name", "-S", "mix"]}
```
Old MixTestInteractive.PortRunner.run/4 will pass the following options to the runner_program:
```elixir
["elixir", "do", "run", "-e", "Application.put_env(:elixir, :ansi_enabled, true);", ",", "--sname", "my-node", "-S", "mix", "test"]
```
Which will cause user to get `no file named "do"` error.
This pull request assembles the command properly so we pass to runner_program:
```elixir
["elixir", "--sname", "my-node", "-S", "mix", "do", "run", "-e", "Application.put_env(:elixir, :ansi_enabled, true);", ",", "test"]
```

Assemble commands correctly on Unix-like systems.

---

lib/mix_test_interactive/runner.ex
test/mix_test_interactive/runner_test.exs

This makes it easier to find when scrolling back.

🚸 Colorize the `Running tests...` message

---

README.md
lib/mix/tasks/test/interactive.ex
lib/mix_test_interactive/command/seed.ex
lib/mix_test_interactive/command_line_parser.ex
lib/mix_test_interactive/command_processor.ex
lib/mix_test_interactive/settings.ex
test/mix_test_interactive/command_line_parser_test.exs
test/mix_test_interactive/command_processor_test.exs
test/mix_test_interactive/end_to_end_test.exs
test/mix_test_interactive/settings_test.exs

I chose to stick with the pattern of single-character commands, looking ahead to a desired future world where we can respond to keystrokes immediately without having to hit `Enter` first.
Since `s` is already taken by the `stale` command, I choose `d` for `see(d)`, since it's the dominant sound in the word.
Rather that having a separate command for clearing the seed, I chose to use `d` with no argument to clear. There are going to be more commands coming that will want to set/clear a value, so this seemed like the best way to get a clear command without eating up more of the single-character command namespace.

✨ Add `d` command for setting/clearing the test seed

---

README.md
lib/mix/tasks/test/interactive.ex
lib/mix_test_interactive/command/exclude.ex
lib/mix_test_interactive/command/include.ex
lib/mix_test_interactive/command/only.ex
lib/mix_test_interactive/command_line_parser.ex
lib/mix_test_interactive/command_processor.ex
lib/mix_test_interactive/settings.ex
test/mix_test_interactive/command_line_parser_test.exs
test/mix_test_interactive/command_processor_test.exs
test/mix_test_interactive/end_to_end_test.exs
test/mix_test_interactive/settings_test.exs

Add new commands for interactively changing tag filters.
- `i` controls the `--include` mix test option
- `o` controls the `--only` mix test option
- `x` controls the `--exclude` mix test option
Closes #31

✨ Add tag filtering

---

README.md
lib/mix_test_interactive/command_line_parser.ex
lib/mix_test_interactive/port_runner.ex
lib/mix_test_interactive/test_runner.ex
test/mix_test_interactive/command_line_parser_test.exs
test/mix_test_interactive/end_to_end_test.exs
test/mix_test_interactive/runner_test.exs

Use the behaviour for all internal implementations including for tests. Also, convert a second DummyRunner to use `start_supervised!`.

✨ Add new TestRunner behaviour for custom runners

---

README.md
lib/mix/tasks/test/interactive.ex
lib/mix_test_interactive/command/max_failures.ex
lib/mix_test_interactive/command_line_parser.ex
lib/mix_test_interactive/command_processor.ex
lib/mix_test_interactive/settings.ex
test/mix_test_interactive/command_line_parser_test.exs
test/mix_test_interactive/command_processor_test.exs
test/mix_test_interactive/end_to_end_test.exs
test/mix_test_interactive/settings_test.exs

Adds a new `m` command for dynamically controlling the `--max-failures` option of `mix test`.

✨ Add m command for max-failures

---

lib/mix_test_interactive/command_line_parser.ex
test/mix_test_interactive/command_line_parser_test.exs

The new command-line parsing in v4.0 wasn't properly handling a command-line that had only patterns/filenames as arguments. We were treating that as empty mti options and ignoring the patterns rather than passing the command line on to be parsed as mix test options.
Fixes #122

🐛 Handle command-line with only patterns

---

README.md

Adds text for running MTI as an independent script.
Useful for working on 3rd party projects that may not want MTI as a `mix.exs` dependency.
Related to issue #126.
Note: I tested many command-line options, and found everything to work except `--breakpoints`.  With `--breakpoints`, the script behaved as if the option was ignored.  I didn't include this detail in the document.  A developer can just call `mix test --breakpoints` if this feature is desired.

Add README documentation for Script Execution (#126)

---

.github/workflows/ci.yml
.tool-versions

Update CI to run on Elixir 1.14 - 1.18 (adding 1.18 and dropping 1.13).
There have been no changes that warrant dropping support for 1.13, so not updating the minimum Elixir version for now.

⬆️ Upgrade to Elixir 1.18.x

---

lib/mix_test_interactive/port_runner.ex
test/mix_test_interactive/port_runner_test.exs

mix_test_interactive automatically enables ANSI output when running on non-Windows systems.
However, the way we were doing it caused the client application to be started when enabling ANSI output and before running the test task.
Rather than using `run -e` to enable ANSI, we now use `eval` instead, which doesn't start the client application.
As part of this work, we also fix a bug where we weren't handling the `--no-start` flag correctly. Previously, we were grabbing that flag (if present) and passing it to the `run` task, but not to the subsequent test task. As a result, the application would still be started in the test task, which is not what the caller would expect.

🚸 Improve ansi-enablement on non-Windows systems

---

README.md
lib/mix/tasks/test/interactive.ex
lib/mix_test_interactive/command_line_parser.ex
lib/mix_test_interactive/config.ex
lib/mix_test_interactive/port_runner.ex
test/mix_test_interactive/command_line_parser_test.exs
test/mix_test_interactive/config_test.exs
test/mix_test_interactive/port_runner_test.exs

Previously, we always enabled ANSI output on Unix-like systems and we didn't on Windows.
However, since Windows 10, ANSI has been available on Windows as well (if the [appropriate registry key is set](https://hexdocs.pm/elixir/IO.ANSI.html)), so we provide a way for users to opt-in if desired.
It is also now possible to run with ANSI output off on Unix-like systems if necessary for any reason.
ANSI output can be enabled/disabled via the `ansi_enabled` configuration setting or the `(no-)ansi-enabled` command line option.
We also modify `PortRunner` to take the `os_type` from ProcessTree instead of passing an argument, which matches the changes we made to Config to support the new setting.
We significantly refactor the PortRunner tests to eliminate many near-duplicate tests.

✨ Make ANSI output configurable

---

README.md
lib/mix/tasks/test/interactive.ex
lib/mix_test_interactive/command_line_formatter.ex
lib/mix_test_interactive/command_line_parser.ex
lib/mix_test_interactive/config.ex
lib/mix_test_interactive/port_runner.ex
test/mix_test_interactive/command_line_formatter_test.exs
test/mix_test_interactive/command_line_parser_test.exs
test/mix_test_interactive/config_test.exs
test/mix_test_interactive/port_runner_test.exs

The new option (off by default) allows you to see the command that will be run just before running the tests. Might be useful to understand what's happening under the hood when diagnosing strange behavior.

Add verbose option/config for printing the test command

---

mix.exs

The tags on the target repository start with a v:
https://github.com/randycoulman/mix_test_interactive/releases

Fix docs source_ref
